using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileUpload.Models;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System.Data;
using System.Text.RegularExpressions;

namespace FileUpload.Controllers
{
    public class MemoController : Controller
    {

        string strPath = System.Web.HttpContext.Current.Server.MapPath("~/Reports/");
        string folderPath = Utilities.MemoStorageRoot;

        ReportsDAL rptDAL = new ReportsDAL();

        [CheckSessionOut]
        public ActionResult Upload()
        {
            

            var mem = new ViewMemo() 
            { 
                memo = new Memo()
            };

            mem.memo.MemoDate = DateTime.Now;
            mem.memo.DocNo = Utilities.GetAutoGeneratedNo(Convert.ToInt32(Session["intMstDepartment"]));
            mem.memo.isSecondSave = false;

            ViewBag.depts = new SelectList(DeptPrefixDAL.GetDepartmentSP(), "ValueMember", "DisplayMember", (int)Session["intMstDepartment"]);
            return View(mem);
        }

        [HttpPost, CheckSessionOut]
        public ActionResult Upload(ViewMemo vm)
        {
                        
            string msg = string.Empty;                    

            try
            {
                if (vm.file.ContentType.ToString().Contains("pdf"))
                {

                    if (vm.file != null)
                    {

                        if (System.IO.Directory.Exists(folderPath) == false)
                        {
                            Directory.CreateDirectory(folderPath);
                        }

                        if (Session["Username"] != null)
                        {
                            var fileName = Utilities.TrimSpaces(vm.file.FileName.Replace("'", ""));
                            var fullPath = Path.Combine(folderPath, Path.GetFileName(fileName));


                            //if (Regex.IsMatch(fileName, @"^[a-zA-Z0-9\s.\?\,\'\;\:\#\@\$\%\^\&\*\!\-]+$"))
                            //{
                            //    msg = "Special Character on the filename is  not allowed. Please rename your file!";
                            //}
                            //else
                            //{

                                if (vm.memo.intMstDepartment == 0)
                                {
                                    vm.memo.intMstDepartment = (int)Session["intMstDepartment"];
                                }

                                ViewBag.depts = new SelectList(DeptPrefixDAL.GetDepartmentSP(), "ValueMember", "DisplayMember", (int)Session["intMstDepartment"]);

                                vm.memo.FileName = fileName;
                                msg = MemoDAL.Save(vm.memo);
                                if (msg.Contains("saved"))
                                {
                                    vm.file.SaveAs(fullPath);
                                    vm.memo.isSecondSave = true;
                                    Session["vm"] = vm;
                                    return RedirectToAction("SendTo");
                                }
                                //else
                                //{
                                //    ViewBag.Msg = msg;
                                //    return View();
                                //}

                            //}
                        }  //end user

                    }
                    else{
                        msg = "No file to upload.";
                    }

                }
                else {
                    msg = "PDF file only.";
                }
                
            }
            catch (Exception ex)
            {
                msg = ex.Message.ToString();
            }

            //ViewBag.depts = new SelectList(DeptPrefixDAL.GetDepartmentSP(), "ValueMember", "DisplayMember", (int)Session["intMstDepartment"]);
            ViewBag.Msg = msg;
            return View(vm);        
           // return RedirectToAction("Upload");
        }

        [CheckSessionOut]
        public ActionResult SendTo()
        {
            var emptySource = new List<ComboBoxSource>();
            var vm = (ViewMemo)Session["vm"];

            //if (Session["vm"] != null)
            //{
                vm.memo.MemoDet = new List<MemoDetail>();   
            //}            

            //Session["vm"] = null;
            //ViewBag.branches = new SelectList(MemoDAL.GetmemoData("", 0, 0, "Branches"), "ValueMember", "DisplayMember");
            //ViewBag.depts = new SelectList(emptySource, "ValueMember", "DisplayMember");
            //ViewBag.pos = new SelectList(emptySource, "ValueMember", "DisplayMember");
            //ViewBag.emps = new SelectList(emptySource, "ValueMember", "DisplayMember");

            string user = Session["Username"].ToString();

            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            //Group Name
            DataSet ds = obj.BindGroupDDL(user);
            ViewBag.gname = ds.Tables[0];
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.gname.Rows)
            {
                items.Add(new SelectListItem { Text = @dr["GroupName"].ToString(), Value = @dr["ID"].ToString() });
            }
            ViewBag.GroupName = items;

            //Other Group
            DataSet ds1 = obj.BindSpecialGroupDDL();
            ViewBag.SpecialGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.SpecialGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["GroupName"].ToString(), Value = @dr["ID"].ToString() });
            }
            ViewBag.SpecialGroup = items1;

            //Branch Group
            DataSet ds2 = obj.BindBranchGroupDDL("", "");
            ViewBag.BranchGroup = ds2.Tables[0];
            List<SelectListItem> items2 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.BranchGroup.Rows)
            {
                items2.Add(new SelectListItem { Text = @dr["BranchName"].ToString(), Value = @dr["BranchCode"].ToString() });
            }
            ViewBag.BranchGroup = items2;

            //Company Group
            DataSet ds3 = obj.BindCompanyGroupDDL("");
            ViewBag.CompanyGroup = ds3.Tables[0];
            List<SelectListItem> items3 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.CompanyGroup.Rows)
            {
                items3.Add(new SelectListItem { Text = @dr["CompanyCode"].ToString(), Value = @dr["intMstCompany"].ToString() });
            }
            ViewBag.CompanyGroup = items3;


            //Department Group
            DataSet ds4 = obj.BindDepartmentGroupDDL("","","");
            ViewBag.DepartmentGroup = ds4.Tables[0];
            List<SelectListItem> items4 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.DepartmentGroup.Rows)
            {
                items4.Add(new SelectListItem { Text = @dr["DepartmentName"].ToString(), Value = @dr["intMstDepartment"].ToString() });
            }
            ViewBag.DepartmentGroup = items4;

            //Position Group
            DataSet ds5 = obj.BindPositionGroupDDL("", "", "");
            ViewBag.PositionGroup = ds5.Tables[0];
            List<SelectListItem> items5 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.PositionGroup.Rows)
            {
                items5.Add(new SelectListItem { Text = @dr["PositionName"].ToString(), Value = @dr["intMstPosition"].ToString() });
            }
            ViewBag.PositionGroup = items5;

            //Employee Group
            DataSet ds6 = obj.BindEmployeeGroupDDL("","","","");
            ViewBag.EmployeeGroup = ds6.Tables[0];
            List<SelectListItem> items6 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.EmployeeGroup.Rows)
            {
                items6.Add(new SelectListItem { Text = @dr["EmployeeName"].ToString(), Value = @dr["intMstEmpPersonal"].ToString() });
            }
            ViewBag.EmployeeGroup = items6;



            return View(vm);
        }

        [HttpPost, CheckSessionOut]
        public ActionResult SendTo(Memo memo)
        {

            string msg = string.Empty;
            bool success = false;

            try
            {
                msg = MemoDAL.SaveUpload(memo);
                if (msg.Contains("saved")) { 
                    success = true;
                    Session["vm"] = null;
                }
            }
            catch (Exception ex)
            {
                success = false;
                msg = ex.Message.ToString();
            }

            return Json(new { success = success.ToString(), msg = msg });
        }

        [HttpGet, CheckSessionOut]
        public ActionResult GetData(string codeMstBranch, int intMstDept, int intMstPosition, string LookFor)
        {
            var data = MemoDAL.GetmemoData(codeMstBranch, intMstDept, intMstPosition, LookFor);

            return Json(data.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet, CheckSessionOut]
        public ActionResult GetUser(string fileName)
        {
            var data = MemoDAL.GetUsers(fileName);

            return Json(data.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet, CheckSessionOut]
        public ActionResult GetMemoList(bool hasEmptyString = false)
        {
            var data = MemoDAL.GetComboMemoList(hasEmptyString);

            return Json(data.ToList(), JsonRequestBehavior.AllowGet);
        }

        [CheckSessionOut]
        public ActionResult Download()
        {
            var dataList = MemoDAL.GetMemoList();
            
            return View(dataList.ToList());
        }

        [CheckSessionOut]
        public FileResult DownloadFile(string id)
        {
            DownloadCounter dlCnt = new DownloadCounter();
            folderPath = Path.Combine(folderPath, id);

            byte[] fileBytes = System.IO.File.ReadAllBytes(folderPath);

            dlCnt.CategoryID = 0;
            dlCnt.FileName = id;
            dlCnt.DownloadedBy = Session["Username"].ToString();
            string strResult = DownloadDAL.AddCount(dlCnt);
            
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, id);
        }

        [CheckSessionOut]
        public ActionResult List()
        {
            var dataList = MemoDAL.GetMemoList();

            return View(dataList.ToList());
        }
        
        [CheckSessionOut]
        public ActionResult Edit(int id)
        {
            var emptySource = new List<ComboBoxSource>();
            var vm = new ViewMemo()
            {
                memo = MemoDAL.GetMemo(id)
            };

            //ViewBag.branches = new SelectList(MemoDAL.GetmemoData("", 0, 0, "Branches"), "ValueMember", "DisplayMember");
            //ViewBag.depts = new SelectList(emptySource, "ValueMember", "DisplayMember");
            //ViewBag.pos = new SelectList(emptySource, "ValueMember", "DisplayMember");
            //ViewBag.emps = new SelectList(emptySource, "ValueMember", "DisplayMember");

            string user = Session["Username"].ToString();

            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            //Group Name
            DataSet ds = obj.BindGroupDDL(user);
            ViewBag.gname = ds.Tables[0];
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.gname.Rows)
            {
                items.Add(new SelectListItem { Text = @dr["GroupName"].ToString(), Value = @dr["ID"].ToString() });
            }
            ViewBag.GroupName = items;
            
            //Other Group
            DataSet ds1 = obj.BindSpecialGroupDDL();
            ViewBag.SpecialGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.SpecialGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["GroupName"].ToString(), Value = @dr["ID"].ToString() });
            }
            ViewBag.SpecialGroup = items1;

            //Branch Group
            DataSet ds2 = obj.BindBranchGroupDDL("","");
            ViewBag.BranchGroup = ds2.Tables[0];
            List<SelectListItem> items2 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.BranchGroup.Rows)
            {
                items2.Add(new SelectListItem { Text = @dr["BranchName"].ToString(), Value = @dr["BranchCode"].ToString() });
            }
            ViewBag.BranchGroup = items2;

            //Company Group
            DataSet ds3 = obj.BindCompanyGroupDDL("");
            ViewBag.CompanyGroup = ds3.Tables[0];
            List<SelectListItem> items3 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.CompanyGroup.Rows)
            {
                items3.Add(new SelectListItem { Text = @dr["CompanyCode"].ToString(), Value = @dr["intMstCompany"].ToString() });
            }
            ViewBag.CompanyGroup = items3;


            //Department Group
            DataSet ds4 = obj.BindDepartmentGroupDDL("", "", "");
            ViewBag.DepartmentGroup = ds4.Tables[0];
            List<SelectListItem> items4 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.DepartmentGroup.Rows)
            {
                items4.Add(new SelectListItem { Text = @dr["DepartmentName"].ToString(), Value = @dr["intMstDepartment"].ToString() });
            }
            ViewBag.DepartmentGroup = items4;

            //Position Group
            DataSet ds5 = obj.BindPositionGroupDDL("", "", "");
            ViewBag.PositionGroup = ds5.Tables[0];
            List<SelectListItem> items5 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.PositionGroup.Rows)
            {
                items5.Add(new SelectListItem { Text = @dr["PositionName"].ToString(), Value = @dr["intMstPosition"].ToString() });
            }
            ViewBag.PositionGroup = items5;

            //Employee Group
            DataSet ds6 = obj.BindEmployeeGroupDDL("", "", "", "");
            ViewBag.EmployeeGroup = ds6.Tables[0];
            List<SelectListItem> items6 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.EmployeeGroup.Rows)
            {
                items6.Add(new SelectListItem { Text = @dr["EmployeeName"].ToString(), Value = @dr["intMstEmpPersonal"].ToString() });
            }
            ViewBag.EmployeeGroup = items6;


            return View(vm);
        }

        [CheckSessionOut]
        public ActionResult Delete(string fileName, int intId)
        {
            string msg = string.Empty;
            var filePath = Path.Combine(folderPath, fileName);

            try
            {
                System.IO.File.Delete(filePath);
                msg = Utilities.DeleteFile(intId, fileName, "Memorandum");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message.ToString());
            }

            return RedirectToAction("List");
        }

        public FileStreamResult PreviewFile(string id)
        {
            Response.AppendHeader("Content-Disposition", "inline; filename=" + id + ";");

            string path = Path.Combine(folderPath, id);
            FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read);
            return File(fs, "application/pdf");
        }

        [HttpGet]
        public ActionResult GetAutoNo(int intMstDepartment)
        {
            var num = Utilities.GetAutoGeneratedNo(intMstDepartment);

            return Json(new { autonum = num }, JsonRequestBehavior.AllowGet);
        }

        [CheckSessionOut]
        public ActionResult ViewReport()
        {
            var emptySource = new List<ComboBoxSource>();            

            ViewBag.memos = new SelectList(emptySource, "ValueMember", "DisplayMember");
            ViewBag.users = new SelectList(emptySource, "ValueMember", "DisplayMember");

            NameOfUploader obj = new NameOfUploader();

            DataSet ds = obj.BindUploaderDDL();
            ViewBag.gname = ds.Tables[0];
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.gname.Rows)
            {
                items.Add(new SelectListItem { Text = @dr["EmployeeName"].ToString(), Value = @dr["intMstEmpPersonal"].ToString() });
            }
            ViewBag.UploadName = items;


            return View();
        }       

        #region Reports
        public void ViewAMDReport(string fileName, string Username)
        {
            ReportDocument rpt = new ReportDocument();
            DataTable dt = new DataTable();
            string moduleName = "Department Order";

            try
            {
                strPath += "rptAMD.rpt";

                if (Username == "null")
                    Username = "";

                dt = rptDAL.GetAMDReport(fileName, Username, moduleName);

                rpt.Load(strPath);

                rpt.SetDataSource(dt);
                rpt.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "AMDReport_" + moduleName);
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }

            rpt.Close();
            rpt.Dispose();
        }

        public void ViewAMSReport(string fileName, DateTime AsofDate)
        {
            ReportDocument rpt = new ReportDocument();
            DataTable dt = new DataTable();
            string moduleName = "Department Order";

            try
            {
                strPath += "rptAMS.rpt";


                dt = rptDAL.GetAMSReport(fileName, AsofDate, moduleName);

                rpt.Load(strPath);

                rpt.SetDataSource(dt);
                rpt.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "AMSReport_" + moduleName);
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }

            rpt.Close();
            rpt.Dispose();
        }

        public void ViewDownloadTrail(string fileName, string userName)
        {
            ReportDocument rpt = new ReportDocument();
            DataTable dt = new DataTable();
            string moduleName = "Department Order";

            try
            {
                strPath += "rptDownloadTrail.rpt";

                if (userName == "null")
                    userName = "";

                dt = rptDAL.GetDownloadTrail(fileName, userName, moduleName);

                rpt.Load(strPath);

                rpt.SetDataSource(dt);
                rpt.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "DownloadTrail");
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }

            rpt.Close();
            rpt.Dispose();
        }

        public void ViewUploadTaggings(int ID)
        {
            ReportDocument rpt = new ReportDocument();
            DataTable dt = new DataTable();
            string moduleName = "Memo";

            try
            {
                strPath += "UploadTaggings.rpt";

                //if (userName == "null")
                //    userName = "";

                dt = rptDAL.GetUploadTaggings(ID, moduleName);

                rpt.Load(strPath);

                rpt.SetDataSource(dt);
                rpt.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "UploadTaggings");
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }
            rpt.Close();
            rpt.Dispose();

        }

        public void ViewUploadFilesSummaryReport(string userID, DateTime DateFrom, DateTime DateTo)
        {
            ReportDocument rpt = new ReportDocument();
            DataTable dt = new DataTable();
            string Type = "Department Order";

            try
            {
                strPath += "ViewUploadFilesSummary.rpt";

                dt = rptDAL.GetUploadFilesSummaryReport(userID, Type, DateFrom, DateTo);

                rpt.Load(strPath);

                rpt.SetDataSource(dt);
                rpt.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "ViewUploadFilesSummary");
            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }

            rpt.Close();
            rpt.Dispose();

        }

        public JsonResult LoadDepartment(string CompanyID, string BranchID, string DepartmentID)
        {
            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            DataSet ds1 = obj.BindDepartmentGroupDDL(CompanyID, BranchID, DepartmentID);
            ViewBag.DepartmentGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.DepartmentGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["DepartmentName"].ToString(), Value = @dr["intMstDepartment"].ToString() });
            }
            //ViewBag.SpecialGroup = items1;

            return Json(items1, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadPosition(string CompanyID, string BranchID, string DepartmentID)
        {
            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            DataSet ds1 = obj.BindPositionGroupDDL(CompanyID, BranchID, DepartmentID );
            ViewBag.PositionGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.PositionGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["PositionName"].ToString(), Value = @dr["intMstPosition"].ToString() });
            }
            //ViewBag.SpecialGroup = items1;

            return Json(items1, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadEmployee(string CompanyID, string BranchID, string DepartmentID, string PositionID)
        {
            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            DataSet ds1 = obj.BindEmployeeGroupDDL(CompanyID, BranchID, DepartmentID, PositionID);
            ViewBag.EmployeeGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.EmployeeGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["EmployeeName"].ToString(), Value = @dr["intMstEmpPersonal"].ToString() });
            }
            //ViewBag.SpecialGroup = items1;

            return Json(items1, JsonRequestBehavior.AllowGet);
        }


        public JsonResult LoadBranch(string CompanyID, string BranchID)
        {
            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            DataSet ds1 = obj.BindBranchGroupDDL(CompanyID, BranchID);
            ViewBag.BranchGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.BranchGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["BranchName"].ToString(), Value = @dr["BranchCode"].ToString() });
            }


            return Json(items1, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadCompany(string CompanyID)
        {

            GroupTaggingHeaderDLL obj = new GroupTaggingHeaderDLL();

            DataSet ds1 = obj.BindCompanyGroupDDL(CompanyID);
            ViewBag.CompanyGroup = ds1.Tables[0];
            List<SelectListItem> items1 = new List<SelectListItem>();
            foreach (System.Data.DataRow dr in ViewBag.CompanyGroup.Rows)
            {
                items1.Add(new SelectListItem { Text = @dr["CompanyCode"].ToString(), Value = @dr["intMstCompany"].ToString() });
            }

            return Json(items1, JsonRequestBehavior.AllowGet);
        }



        #endregion

    }
}
